---
- name: configure nginx
  hosts:  all
  become: true
  handlers:
  - name: reload nginx
    service:
      name:  nginx
      state: reloaded

  tasks:
  - name: install nginx
    package:
      name:
      - nginx
      - python3-certbot-nginx

  - name: create app directory
    file:
      path:  /app
      state: directory

  - name: create https directory
    file:
      path:  /app/https
      state: directory
      owner: root
      group: www-data
      mode:  0750

  - name: create private key
    community.crypto.openssl_privatekey:
      path:  /app/https/boltzmann.key
      owner: root
      group: www-data
      mode:  0640

  - name: create self-signed certificate
    community.crypto.x509_certificate:
      path:            /app/https/boltzmann.pem
      privatekey_path: /app/https/boltzmann.key
      provider:        selfsigned
      owner:           root
      group:           www-data
      mode:            0644

  - name: remove default site
    file:
      path:  /etc/nginx/sites-enabled/default
      state: absent
    notify: reload nginx

  - name: add boltzmann nginx config
    template:
      src:  templates/boltzmann.nginx.conf
      dest: /etc/nginx/sites-enabled/boltzmann.conf
    notify: reload nginx

  - name: start nginx
    service:
      name:    nginx
      state:   started
      enabled: true
